### Get all the blogs
GET http://localhost:8080/api/blogs

### Create an entry for a new blog
POST http://localhost:8080/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGU5OTEyIiwiaWQiOiI2NzA1MzdhOGI4MTJkZDRkYzdhOWYzMTkiLCJpYXQiOjE3MjgzOTkxOTB9.oW2CBYiOtXbvd0FQqmceD6vlLcNnaT94BwWwYmyDfqU

{
    "title": "Hola2",
    "author": "Helena Ruano",
    "url": "https://midu.dev/to-reversed-to-spliced-to-sorted-with/",
    "userId": "670447bf488c3a180d826e9a"
}

### Updates the likes of a blog
PUT http://localhost:8080/api/blogs/670480377a21e5ea1174f7aa
Content-Type: application/json

{
    "title": "Hola5",
    "author": "Miguel Angel Durán García",
    "url": "https://midu.dev/to-reversed-to-spliced-to-sorted-with/",
    "likes": 2,
    "userId": "670447bf488c3a180d826e9a"
}

### Delete a blog
DELETE  http://localhost:8080/api/blogs/6705477dc58795c1bc0b059f
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhlbGU5OTEyIiwiaWQiOiI2NzA1MzdhOGI4MTJkZDRkYzdhOWYzMTkiLCJpYXQiOjE3MjgzOTkxOTB9.oW2CBYiOtXbvd0FQqmceD6vlLcNnaT94BwWwYmyDfqU
